#!/bin/bash

source /etc/version
board_sn=$(/etc/init.d/boardsn)
board_name=$(cat /etc/board)

test -n "$os_debug" || source /etc/init.d/conf

msg_begin() {
    echo -n " * $1: "
}

msg_done() {
    test -n "$1" && echo $1 || echo "done"
}

msg_fail() {
    test -n "$1" && echo $1 || echo "failed"
}

msg_background() {
    test -n "$1" && echo $1 || echo "pending"
}

panic_action() {
    logger -t panic -s "rebooting"
    /sbin/reboot
}

