#!/bin/bash

_sys_conf="/etc/os.conf"
_boot_conf="/boot/os.conf"
_conf="/data/etc/os.conf"

if ! [ -f $_conf ]; then
    if [ -f $_boot_conf ]; then
        cp $_boot_conf $_conf
    elif [ -f $_sys_conf ]; then
        cp $_sys_conf $_conf
    fi
fi

source $_conf

