#!/bin/bash

_sys_conf="/etc/os.conf"
_boot_conf="/boot/os.conf"
_conf="/data/etc/os.conf"

if ! [ -d /data/etc ]; then
    # use boot/system variants if we don't have the data partition mounted
    if [ -f $_boot_conf ]; then
        source $_boot_conf
    elif [ -f $_sys_conf ]; then
        source $_sys_conf
    fi

    return
fi

if ! [ -f $_conf ]; then
    if [ -f $_boot_conf ]; then
        cp $_boot_conf $_conf
    elif [ -f $_sys_conf ]; then
        cp $_sys_conf $_conf
    fi
fi

if [ -f $_conf ]; then
    source $_conf
fi

