#!/bin/bash

sys_conf="/etc/os.conf"
conf="/data/etc/os.conf"

if [ -f $sys_conf ] && ! [ -f $conf ]; then
    cp $sys_conf $conf
fi

if [ -f $conf ]; then
    source $conf
fi

mount_all() {
    echo -n "Mounting filesystems: "

    /bin/mkdir -p /dev/pts
    /bin/mkdir -p /dev/shm
    /bin/mount --make-shared /
    /bin/mount -a

    echo "done"

    if [ "$os_debug" == "true" ]; then
        echo -n "Remounting boot partition read-write: "
        mount -o remount,rw /boot
        [ $? == 0 ] && echo "done" || echo "failed"

        echo -n "Remounting root partition read-write: "
        mount -o remount,rw /
        [ $? == 0 ] && echo "done" || echo "failed"
    fi
}

unmount_all() {
    /bin/umount -a -r
    /sbin/swapoff -a
}

set_hostname() {
    echo -n "Setting hostname: "

    if [ -f /data/etc/hostname ]; then
        hostname=$(cat /data/etc/hostname)
    else
        hostname="$os_prefix-$board_sn"
    fi

    /bin/hostname $hostname
    echo "127.0.0.1 localhost $hostname" > /etc/hosts

    echo "done"
}

load_modules() {
    echo -n "Loading kernel modules: "

    if [ -r /etc/modules ]; then
        cat /etc/modules | while read line; do test -n "$line" && /sbin/modprobe $line; done
    fi

    if [ -r /data/etc/modules ]; then
        cat /data/etc/modules | while read line; do test -n "$line" && /sbin/modprobe $line; done
    fi

    echo "done"
}

start() {
    mount_all
    set_hostname
    load_modules
}

stop() {
    unmount_all
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?

