#!/bin/bash

sys_conf="/etc/os.conf"
boot_conf="/boot/os.conf"
conf="/data/etc/os.conf"

test -n "$os_version" || source /etc/init.d/base

mount_fs() {
    msg_begin "Mounting filesystems"
    /bin/mount -a
    test $? == 0 && msg_done || msg_fail

    if ! [ -f $conf ]; then
        if [ -f $boot_conf ]; then
            cp $boot_conf $conf
        elif [ -f $sys_conf ]; then
            cp $sys_conf $conf
        fi
    fi

    if [ -f $conf ]; then
        source $conf
    fi

    if [ "$os_debug" == "true" ]; then
        msg_begin "Remounting boot partition read-write"
        mount -o remount,rw /boot
        test $? == 0 && msg_done || msg_fail

        msg_begin "Remounting root partition read-write"
        mount -o remount,rw /
        test $? == 0 && msg_done || msg_fail
    fi
}

mk_tty_login() {
    test -z "$os_tty_login" && os_tty_login=tty1
    ln -sf /dev/$os_tty_login /dev/ttylogin
}

case "$1" in
    start)
        mount_fs
        mk_tty_login
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?

