#!/bin/sh

test -c /dev/watchdog || exit 0

case "$1" in
    start)
        echo -n "Starting watchdog: "
        watchdog -t 5 /dev/watchdog
        [ $? == 0 ] && echo "done" || echo "failed"
        ;;

    stop)
        echo -n "Stopping watchdog: "
        kill `pidof watchdog` 2>/dev/null
        [ $? == 0 ] && echo "done" || echo "failed"
        ;;

    restart|reload)
        ;;

    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

