#!/bin/bash

SYS_HOSTNAME_FILE="/etc/hostname"
BOOT_HOSTNAME_FILE="/boot/hostname"
HOSTNAME_FILE="/data/etc/hostname"


test -n "$OS_VERSION" || source /etc/init.d/base

case "$1" in
    start)
        msg_begin "Setting hostname"

        prepare_conf $HOSTNAME_FILE $SYS_HOSTNAME_FILE $BOOT_HOSTNAME_FILE

        if [[ -f $HOSTNAME_FILE ]]; then
            hostname=$(cat $HOSTNAME_FILE)
        else
            hostname="$OS_PREFIX-$BOARD_SN"
        fi

        /bin/hostname $hostname
        echo "127.0.0.1 localhost $hostname" > /etc/hosts

        msg_done
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?

