#!/bin/bash

sys_hostname_file="/etc/hostname"
boot_hostname_file="/boot/hostname"
hostname_file="/data/etc/hostname"

test -n "$os_version" || source /etc/init.d/base

case "$1" in
    start)
        msg_begin "Setting hostname"

        prepare_conf $hostname_file $sys_hostname_file $boot_hostname_file

        if [[ -f $hostname_file ]]; then
            hostname=$(cat $hostname_file)
        else
            hostname="$os_prefix-$board_sn"
        fi

        /bin/hostname $hostname
        echo "127.0.0.1 localhost $hostname" > /etc/hosts

        msg_done
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?

