#!/bin/bash

case "$1" in
    start)
	    msg_begin "Starting logging"
    	start-stop-daemon -b -S -q -m -p /var/run/syslogd.pid --exec /sbin/syslogd -- -n
	    msg_done
	    ;;

    stop)
	    msg_begin "Stopping logging"
	    start-stop-daemon -K -q -p /var/run/syslogd.pid
    	msg_done
	    ;;

    *)
	    echo "Usage: $0 {start|stop}"
    	exit 1
esac

exit $?

