#!/bin/bash

test -n "$os_version" || source /etc/init.d/base

case "$1" in
    start)
        msg_begin "Starting syslogd"
        syslogd
        test $? == 0 && msg_done || msg_fail
        ;;

    stop)
        msg_begin "Stopping syslogd"
        killall syslogd &>/dev/null
        test $? == 0 && msg_done || msg_fail
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?

