#!/bin/bash

test -n "$OS_VERSION" || source /etc/init.d/base

DMESG_LOG="/var/log/dmesg.log"


case "$1" in
    start)
        msg_begin "Starting syslogd"
        syslogd
        test $? == 0 && msg_done || msg_fail
        echo "---- booting $OS_NAME $OS_VERSION ----" >> $DMESG_LOG
        dmesg -T -w >> $DMESG_LOG &
        ;;

    stop)
        msg_begin "Stopping syslogd"
        killall syslogd &>/dev/null
        test $? == 0 && msg_done || msg_fail
        killall dmesg &>/dev/null
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?

