#!/bin/bash

# these aren't used in this file but
# throughout various init scripts
sys_watch_conf="/etc/watch.conf"
watch_conf="/data/etc/watch.conf"

if [ -f $sys_watch_conf ] && ! [ -f $watch_conf ]; then
    cp $sys_watch_conf $watch_conf
fi

test -c /dev/watchdog || exit 0

case "$1" in
    start)
        msg_begin "Starting watchdog"
        watchdog -t 5 /dev/watchdog
        test $? == 0 && msg_done || msg_fail
        ;;

    stop)
        msg_begin "Stopping watchdog"
        killall watchdog &>/dev/null
        test $? == 0 && msg_done || msg_fail
        ;;

    *)
        echo $"Usage: $0 {start|stop}"
        exit 1
esac

exit $?

