#!/bin/bash

disk_dev="/dev/mmcblk0"
data_dev="${disk_dev}p3"

test -b $data_dev && exit 0

case "$1" in
    start)
        msg_begin "Creating data partition"
        echo -e "n
            p
            3
            \n
            \n
            w" | /sbin/fdisk $disk_dev >/dev/null
        test $? == 0 && msg_done || msg_fail
        sync
        partx -a $disk_dev &>/dev/null

        msg_begin "Formatting data partition"
        mkfs.ext4 $data_dev
        test $? == 0 && msg_done || msg_fail
        
        msg_begin "Mounting data partition"
        mount /data
        test $? == 0 && msg_done || msg_fail

        msg_begin "Creating required data files"
        mkdir /data/etc
        mkdir /data/log
        mkdir -m 775 /data/output
        mkdir -m 775 /data/media

        ln -s /usr/share/zoneinfo/UTC /data/etc/localtime
        msg_done

        # mount other partitions depending on data
        mount -a
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?

