#!/bin/bash

DISK_DEV="/dev/mmcblk0"
DATA_DEV="${DISK_DEV}p3"

start() {
    echo "Setting up data partition"

    # if the data partition is not present, create and format it
    if ! [ -b $DATA_DEV ]; then
        echo "Creating data partition"
        echo -e "n
    p
    3
    \n
    \n
    w
    " | /sbin/fdisk $DISK_DEV
        sync
        partx -a $DISK_DEV &>/dev/null

        echo "Formatting data partition"
        mkfs.ext4 $DATA_DEV
        
        echo "Mounting data partition"
        mount /data
    fi
    
    if df /dev/mmcblk0p3 >/dev/null 2>&1; then
        # make sure required directories exist
        mkdir -p /data/etc
        mkdir -p /data/log
        mkdir -p /data/output
        mkdir -p /data/media
        chmod 775 /data/output
        chmod 775 /data/media
        
        # mount any partitions depending on data folders
        mount -a

        # make sure a localtime symlink exists
        if ! [ -e /data/etc/localtime ]; then
            ln -s /usr/share/zoneinfo/UTC /data/etc/localtime
        fi

        # make sure root and admin users exist
        touch /data/etc/shadow
        chmod go-rwx /data/etc/shadow
        if ! grep root /data/etc/shadow &>/dev/null; then
            echo 'root::::::::' >> /data/etc/shadow
        fi
        if ! grep admin /data/etc/shadow &>/dev/null; then
            echo 'admin::::::::' >> /data/etc/shadow
        fi

        # set root and admin passwords
        if [ -f /data/etc/motion.conf ]; then
            password=$(cat /data/etc/motion.conf | grep admin_password | cut -d ' ' -f 3-)
        fi
        if [ -z "$password" ]; then
            echo "Setting empty admin password"
        else
            echo "Setting custom root/admin password"
        fi

        rm -f /data/etc/shadow+

        echo -en "$password\n$password\n" | passwd &>/dev/null # root
        echo -en "$password\n$password\n" | passwd admin &>/dev/null # admin
        
        sed -r -i 's/root:([^:]+):[[:digit:]]+:/root:\1::/' /data/etc/shadow # removes pwd expiration
        sed -r -i 's/admin:([^:]+):[[:digit:]]+:/admin:\1::/' /data/etc/shadow # removes pwd expiration

        # copy common sys config files
        if [ -f /etc/watch.conf ] && ! [ -f /data/etc/watch.conf ]; then
            cp /etc/watch.conf /data/etc/watch.conf
        fi
    fi
}

case "$1" in
    start)
        start
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?

