#!/bin/bash

sys_conf="/etc/bluetooth.conf"
boot_conf="/boot/bluetooth.conf"
conf="/data/etc/bluetooth.conf"

if ! [ -f $conf ]; then
    if [ -f $boot_conf ]; then
        cp $boot_conf $conf
    elif [ -f $sys_conf ]; then
        cp $sys_conf $conf
    fi
fi

test -f $conf || exit 0

test -n "$os_version" || source /etc/init.d/base

hci=hci0
bluetoothd=/usr/libexec/bluetooth/bluetoothd

start() {
    msg_begin "Starting bluetooth"

    # wait up to 10 seconds for device
    count=0
    while ! hciconfig $hci &>/dev/null; do
        sleep 1
        count=$(($count + 1))
        if [ $count -ge 10 ]; then
            msg_fail "no device"
            logger -t bluetooth -s "bluetooth device not available, rebooting"
            reboot
            return 1
        fi
    done

    /usr/libexec/bluetooth/bluetoothd &>/dev/null &
    msg_done
}

stop() {
    msg_begin "Stopping bluetooth"
    killall bluetoothd &>/dev/null
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;
        
    stop)
        stop
        ;;
        
    restart)
        stop
        start
        ;;
    
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

