#!/bin/bash

sys_conf="/etc/firewall.sh"
boot_conf="/boot/firewall.sh"
conf="/data/etc/firewall.sh"

test -n "$os_version" || source /etc/init.d/base

prepare_conf $conf $sys_conf $boot_conf
test -f $conf || exit 0

start() {
    msg_begin "Starting firewall"

    bash $conf  

    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;
        
    stop)
        ;;
        
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

