#!/bin/bash

SYS_CONF="/etc/crontabs"
CONF="/data/etc/crontabs"

PROG="/usr/sbin/crond"


test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base


start() {
    msg_begin "Starting crond"
    
    if [[ -d ${SYS_CONF} ]];  then
        ${PROG} -c ${SYS_CONF}
    fi

    mkdir -p ${CONF}
    ${PROG} -c ${CONF}

    test $? == 0 && msg_done || msg_fail
}

stop() {
    msg_begin "Stopping crond"
    killall -q $(basename ${PROG})
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;
    
    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

