#!/bin/bash

SYS_CONF="/etc/crontabs"
CONF="/data/etc/crontabs"

test -n "$os_version" || source /etc/init.d/base

start() {
    msg_begin "Starting crond"
    
    if [[ -d $SYS_CONF ]];  then
        /usr/sbin/crond -c $SYS_CONF
    fi

    mkdir -p $CONF
    /usr/sbin/crond -c $CONF

    test $? == 0 && msg_done || msg_fail
}

stop() {
    msg_begin "Stopping crond"
    killall crond &>/dev/null
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;
    
    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

