#!/bin/bash

CONF="/etc/proftpd.conf"
PROG="/usr/sbin/proftpd"


test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base
test -n "${OS_DEBUG}" || source /etc/init.d/conf

test -s ${CONF} || exit 0


start() {
    msg_begin "Starting proftpd"
    mkdir -p /var/run/proftpd
    touch /var/log/wtmp
    ${PROG} &>/dev/null
    test $? == 0 && msg_done || msg_fail
}

stop() {
    msg_begin "Stopping proftpd"
    killall -q $(basename ${PROG})
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;
    
    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

