#!/bin/bash

test -f /etc/samba/smb.conf || exit 0

test -n "$os_version" || source /etc/init.d/base
test -n "$os_debug" || source /etc/init.d/conf

test "$os_networkless" == "true" && exit 0

start() {
    mkdir -p /var/log/samba
    mkdir -p /var/lib/samba/private

    msg_begin "Starting smbd"
    smbd -D
    test $? == 0 && msg_done || msg_fail

    msg_begin "Starting nmbd"
    nmbd -D
    test $? == 0 && msg_done || msg_fail
}

stop() {
    msg_begin "Stopping smbd"
    killall smbd &>/dev/null
    test $? == 0 && msg_done || msg_fail

    msg_begin "Stopping nmbd"
    killall nmbd &>/dev/null
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

