#!/bin/bash

SYS_CONF="/etc/mongodb.conf"
BOOT_CONF="/boot/mongodb.conf"
CONF="/data/etc/mongodb.conf"

PROG="/usr/bin/mongod"


test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base

prepare_conf ${CONF} ${SYS_CONF} ${BOOT_CONF}
test -f ${CONF} || exit 0


start() {
    msg_begin "Starting mongod"
    db_dir=$(cat ${CONF} | grep dbpath | cut -d '=' -f 2)
    mkdir -p ${db_dir}
    ${PROG} -f ${CONF} --fork > /dev/null
    test $? == 0 && msg_done || msg_fail
}

stop() {
    msg_begin "Stopping mongod"
    killall -q $(basename ${PROG})
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

