#!/bin/bash

SYS_CONF="/etc/redis.conf"
BOOT_CONF="/boot/redis.conf"
CONF="/data/etc/redis.conf"

PROG="/usr/bin/redis-server"


test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base

prepare_conf ${CONF} ${SYS_CONF} ${BOOT_CONF}
test -s ${CONF} || exit 0


start() {
    msg_begin "Starting redis"
    db_dir=$(cat ${CONF} | grep -E '^dir' | cut -d ' ' -f 2)
    mkdir -p ${db_dir}
    ${PROG} ${CONF}
    test $? == 0 && msg_done || msg_fail
}

stop() {
    msg_begin "Stopping redis"
    killall -q $(basename ${PROG})
    test $? == 0 && msg_done || msg_fail
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

