#!/bin/sh

sys_conf="/etc/motioneye.conf"
conf="/data/etc/motioneye.conf"
watch_timeout=120
dev_v4l_by_id="/dev/v4l/by-id/"

if [ -f $sys_conf ] && ! [ -f $conf ]; then
    mkdir -p $(dirname $conf)
    cp $sys_conf $conf
fi

if [ -f "$conf" ]; then
    opts=$(cat "$conf" | while read line; do echo "--$line"; done)
    port=$(echo "$opts" | grep -oE 'port [[:digit:]]+' | cut -d ' ' -f 2)
else
    echo "configuration file not present"
    exit 0
fi

responsive() {
    if wget -q -t 1 -T 2 -O - http://127.0.0.1:$port/static/img/motioneye-logo.svg >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

watch() {
    count=0
    while true; do
        sleep 5
        if responsive; then
            count=0
        else
            if [ $count -lt $watch_timeout ]; then
                count=$(($count + 5))
            else
                logger -t motioneye -s "not responding for $watch_timeout seconds, rebooting"
                reboot
            fi
        fi
    done
}

find_persistent_device() {
    device=$1

    if ! [ -d $dev_v4l_by_id ]; then
        echo $device
        return
    fi

    for p in $dev_v4l_by_id/*; do
        if [ $(realpath "$p") == $device ]; then
            echo $p | sed 's#//*#/#g'
            return
        fi
    done
    
    echo $device
}

start() {
    echo -n "Starting motioneye: "
    meyectl startserver -b -c $conf -l

    count=0
    while true; do
        sleep 1

        if responsive; then
            break
        fi

        if [ $count -gt $watch_timeout ]; then
            echo "failed"
	    reboot
            return
        fi

        count=$(($count + 1))
    done

    # add connected camera(s) with default settings
    if responsive && ! [ -f /data/etc/motion.conf ]; then
        count=$(ls /dev/video* 2>/dev/null | wc -l)
        index=1
        for device in $(ls /dev/video* 2>/dev/null); do
            if [ "$count" -gt "1" ]; then
                output_dir="/data/output/camera$index/"
            else
                output_dir="/data/output/"
            fi
            loc="/config/add/?_username=admin"
            device=$(find_persistent_device $device)
            body="{\"path\": \"$device\", \"proto\": \"v4l2\"}"
            signature=$(echo -n "POST:$loc:$body:" | sha1sum | cut -d ' ' -f 1)

            curl -s -m 60 --data "$body" "http://127.0.0.1:$port$loc&_signature=$signature" > /dev/null
            index=$(($index + 1))
        done
    fi

    watch &

    echo "done"
}

stop() {
    echo -n "Shutting down motioneye: "
    meyectl stopserver &>/dev/null && echo "done" || echo "failed"
    ps | grep motioneye | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

