#!/bin/bash

USERINIT="/data/etc/userinit.sh"


test -f ${USERINIT} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base

case "$1" in
    start)
        msg_begin "Executing user init script"
        /bin/bash ${USERINIT}
        test $? == 0 && msg_done || msg_fail
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?

