#!/bin/sh

case "$1" in
	start)
		printf "Starting logging: "
		/sbin/syslogd -m 0
		/sbin/klogd
		echo "OK"
		;;
	stop)
		printf "Stopping logging: "
		[ -f /var/run/klogd.pid ] && kill `cat /var/run/klogd.pid`
		[ -f /var/run/syslogd.pid ] && kill `cat /var/run/syslogd.pid`
		echo "OK"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
