#!/bin/sh
#
# Starts syslog.
#



umask 077

start() {
 	echo -n "Starting syslogd: "
	start-stop-daemon -S -q -p /var/run/syslog.pid -x /sbin/syslogd -- -m 0
	echo "OK"

	echo -n "Starting klogd: "
	start-stop-daemon -S -q -p /var/run/klogd.pid -x /sbin/klogd
	echo "OK"
}
stop() {
	echo -n "Stopping klogd: "
	start-stop-daemon -K -n klogd
	echo "OK"

	echo -n "Stopping syslogd: "
	start-stop-daemon -K -n syslogd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
