#!/bin/sh

case "$1" in
	start)
		echo -n "Starting web2py: "
		start-stop-daemon -S -q -m -p /run/web2py.pid \
			-c www-data \
			-b -x /var/www/web2py/web2py.py \
			-- --nogui -a '"<recycle>"' -i 0.0.0.0 -p 8000
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		echo -n "Stopping web2py: "
		start-stop-daemon -K -q -p /run/web2py.pid
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart)
		"$0" stop
		sleep 1
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		;;
esac
