#!/bin/sh

NAME="nslcd"
DAEMON="/usr/sbin/${NAME}"

case "$1" in
start)
        echo -n "Starting ${NAME}: "
        start-stop-daemon -S -x ${DAEMON}
        [ $? -eq 0 ] && echo "OK" || echo "FAIL"
        ;;
stop)
        echo -n "Stopping ${NAME}: "
        start-stop-daemon -K -x ${DAEMON}
        [ $? -eq 0 ] && echo "OK" || echo "FAIL"
        ;;
restart|reload)
        $0 stop
        $0 start
        ;;
*)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

