#!/bin/sh
#
# Starts at daemon
#

umask 077

start() {
	echo -n "Starting atd: "
	start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/atd.pid --background --exec /usr/sbin/atd -- -f
	echo "OK"
}
stop() {
	echo -n "Stopping atd: "
	start-stop-daemon --stop --quiet --pidfile /var/run/atd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
