HIAWATHA_VERSION = 8.1
HIAWATHA_SITE = http://www.hiawatha-webserver.org/files/

ifeq ($(BR2_PACKAGE_HIAWATHA_SSL),y)
HIAWATHA_CONF_OPT += -DENABLE_SSL_EXTERNAL=ON -DENABLE_SSL=ON
HIAWATHA_DEPENDENCIES += polarssl
endif

HIAWATHA_CONF_OPT += \
	-DENABLE_TOOLKIT=OFF \
	-DENABLE_XSLT=OFF

$(eval $(call CMAKETARGETS))
