#!/bin/sh
#
# Start/stop exim
#

PIDFILE=/var/lock/exim/exim-daemon.pid

case "$1" in
  start)
	echo "Starting exim..."
	start-stop-daemon -S -x exim -- -bd
	;;
  stop)
	echo -n "Stopping exim..."
	start-stop-daemon -K -o -p $PIDFILE
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
