#!/bin/sh
#
# Start/stop exim
#

PIDFILE=/var/run/exim/exim.pid

case "$1" in
  start)
	echo "Starting exim..."
	if [ ! -d /var/log/exim ]; then
	  mkdir -p /var/log/exim
	  chown exim:mail /var/log/exim
	fi
	if [ ! -d /var/run/exim ]; then
	  mkdir -p /var/run/exim
	  chown root:mail /var/run/exim
	fi
	start-stop-daemon -S -x exim -- -bd
	;;
  stop)
	printf "Stopping exim..."
	start-stop-daemon -K -o -p $PIDFILE
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
