#############################################################
#
# lzo
#
#############################################################
LZO_VERSION:=2.03
LZO_SOURCE:=lzo-$(LZO_VERSION).tar.gz
LZO_SITE:=http://www.oberhumer.com/opensource/lzo/download
LZO_CONF_OPT = --enable-shared
HOST_LZO_CONF_OPT = --enable-shared
LZO_AUTORECONF = NO

# lzo's configure was generated by an old autoconf, and the
# AC_CANONICAL_TARGET check fails in host-lzo when the cache has been
# filled with ac_cv_build and ac_cv_host.
HOST_LZO_AUTORECONF = YES

LZO_INSTALL_STAGING = YES
LZO_INSTALL_TARGET = YES
LZO_INSTALL_STAGING_OPT = CC="$(TARGET_CC)" DESTDIR=$(STAGING_DIR) install

$(eval $(call AUTOTARGETS,package,lzo))
$(eval $(call AUTOTARGETS,package,lzo,host))
