#!/bin/sh

# Server-side demuxing by default
IIOD_OPTS=-D

[ -r /etc/default/iiod ] && . /etc/default/iiod

case "$1" in
	start)
		echo "Starting IIO Server Daemon"
		start-stop-daemon -S -b -q -m -p /var/run/iiod.pid -x /usr/sbin/iiod -- $IIOD_OPTS
		exit $?
		;;

	stop)
		echo "Stopping IIO Server Daemon"
		start-stop-daemon -K -q -p /var/run/iiod.pid 2>/dev/null
		exit $?
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
