#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

BOOT_DEV=/dev/mmcblk0p1
ROOT_DEV=/dev/mmcblk0p2
DATA_DEV=/dev/mmcblk0p3

FW_DIR=/data/.fwupdate
FW_FILE=firmware.img.gz
FW_FILE_EXTR=firmware.img

ROOT_INFO_FILE=root_info

msg() {
    echo "* $1"
}

on_exit() {
    msg "Switching to normal boot"
    /remove_initramfs

    msg "Unmounting data partition"
    umount /data
    
    msg "Unmounting boot partition"
    umount /boot
    
    msg "Syncing"
    sync
    
    msg "Rebooting"
    echo 'b' > /proc/sysrq-trigger
}

trap on_exit EXIT

msg "Waiting for sdcard"
sleep 2

msg "Mounting pseudo filesystems"
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc

msg "Mounting boot partition"
mount $BOOT_DEV /boot

msg "Mounting data partition"
mount $DATA_DEV /data

if ! [ -r $FW_DIR/$FW_FILE_EXTR ]; then
    msg "No firmware found, aborting"
    exit 1
fi

if ! [ -r $FW_DIR/$ROOT_INFO_FILE ]; then
    msg "No root partition info, aborting"
    exit 1
fi

msg "Copying root image"
root_start=$(cat $FW_DIR/$ROOT_INFO_FILE | cut -d ' ' -f 1)
root_size=$(cat $FW_DIR/$ROOT_INFOO_FILE | cut -d ' ' -f 2)

dd if=$FW_DIR/$FW_FILE_EXTR skip=$root_start of=$ROOT_DEV bs=1048576 count=$root_size || exit 1

msg "Cleaning up"
rm -rf $FW_DIR

