#!/bin/sh

NAME="nscd"
DAEMON="/usr/sbin/${NAME}"
PID_F="/var/run/nscd/${NAME}.pid"

case "$1" in
start)
        printf "Starting ${NAME}: "
        start-stop-daemon -S -p ${PID_F} -x ${DAEMON}
        [ $? -eq 0 ] && echo "OK" || echo "FAIL"
        ;;
stop)
        printf "Stopping ${NAME}: "
        start-stop-daemon -K -p ${PID_F}
        [ $? -eq 0 ] && echo "OK" || echo "FAIL"
        ;;
restart|reload)
        $0 stop
        $0 start
        ;;
*)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac
