#!/bin/sh
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/sbin/l2tpd
PIDFILE=/var/run/l2tpd.pid

test -f $DAEMON || exit 0

case "$1" in
  start)
    start-stop-daemon --start  --pidfile $PIDFILE --exec $DAEMON -- -D &
    ;;
  stop)
    start-stop-daemon --stop  --pidfile $PIDFILE --exec $DAEMON
    ;;
  restart|force-reload)
    start-stop-daemon --stop  --pidfile $PIDFILE --exec $DAEMON 
    sleep 1
    start-stop-daemon --start  --pidfile $PIDFILE --exec $DAEMON
    ;;
  *)
    echo "Usage: /etc/init.d/l2tdp {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
