#!/bin/sh
#
# Starts dante
#

# Allow a few customizations from a config file
test -r /etc/default/dante && . /etc/default/dante

start() {
	printf "Starting dante: "
	start-stop-daemon -S -q -p /var/run/dante.pid \
		--exec /usr/sbin/sockd -- $DAEMON_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping dante: "
	start-stop-daemon -K -q -p /var/run/dante.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
