#!/bin/sh

if [ -r /etc/modules ]; then
    cat /etc/modules | while read line; do test -n "$line" && /sbin/modprobe $line; done
fi

if [ -r /data/etc/modules ]; then
    cat /data/etc/modules | while read line; do test -n "$line" && /sbin/modprobe $line; done
fi

exit 0

