#!/bin/sh

RADVD=/usr/sbin/radvd

echo "1" > /proc/sys/net/ipv6/conf/all/forwarding

echo -n "Starting radvd: "
if [ ! -x "${RADVD}" ]; then
	echo "missing"
	exit 1
fi

if ${RADVD} ; then
	echo "done"
else
	echo "failed"
	exit 1
fi
