#!/bin/sh
#
# Set up frame buffer
#

case "$1" in
    start)
        echo "Setting up display..."
        /usr/sbin/odroidc2_init_fb.sh
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
