#!/bin/sh
#
# Starts stunnel
#

start() {
	echo -n "Starting stunnel: "
	start-stop-daemon -S -q -p /var/run/stunnel.pid --exec /usr/bin/stunnel
	echo "OK"
}
stop() {
	echo -n "Stopping stunnel: "
	start-stop-daemon -K -q -p /var/run/stunnel.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
