#############################################################
#
# v4l2rtspserver
#
#############################################################

V4L2RTSPSERVER_VERSION = master
V4L2RTSPSERVER_SITE = https://github.com/mpromonet/v4l2rtspserver.git
V4L2RTSPSERVER_SITE_METHOD = git
V4L2RTSPSERVER_GIT_SUBMODULES = YES
V4L2RTSPSERVER_LICENSE = UNLICENSE
V4L2RTSPSERVER_LICENSE_FILES = LICENSE
V4L2RTSPSERVER_INSTALL_TARGET = YES
V4L2RTSPSERVER_DEPENDENCIES = v4l2cpp
V4L2RTSPSERVER_CFLAGS = $(TARGET_CFLAGS)

define V4L2RTSPSERVER_COPY_INCLUDE_FILES
	cp $(BUILD_DIR)/v4l2cpp-$(V4L2CPP_VERSION)/*.a $(BUILD_DIR)/v4l2rtspserver-$(V4L2RTSPSERVER_VERSION)/
	cp $(BUILD_DIR)/v4l2cpp-$(V4L2CPP_VERSION)/inc/* $(BUILD_DIR)/v4l2rtspserver-$(V4L2RTSPSERVER_VERSION)/inc/
endef

V4L2RTSPSERVER_PRE_CONFIGURE_HOOKS += V4L2RTSPSERVER_COPY_INCLUDE_FILES

define V4L2RTSPSERVER_RENAME_BINARY
	mv $(TARGET_DIR)/usr/bin/v4l2rtspserver-$(V4L2RTSPSERVER_VERSION) $(TARGET_DIR)/usr/bin/v4l2rtspserver
endef

V4L2RTSPSERVER_POST_INSTALL_TARGET_HOOKS += V4L2RTSPSERVER_RENAME_BINARY

ifeq ($(BR2_STATIC_LIBS),y)
V4L2RTSPSERVER_CONFIG_TARGET = linux
V4L2RTSPSERVER_LIBRARY_LINK = $(TARGET_AR) cr
else
V4L2RTSPSERVER_CONFIG_TARGET = linux-with-shared-libraries
V4L2RTSPSERVER_LIBRARY_LINK = $(TARGET_CC) -o
V4L2RTSPSERVER_CFLAGS += -fPIC
endif

ifndef ($(BR2_ENABLE_LOCALE),y)
V4L2RTSPSERVER_CFLAGS += -DLOCALE_NOT_USED
endif

$(eval $(cmake-package))
