#!/bin/sh

MYSQL_DIR="/var/mysql"
MYSQL_USER="mysql"

[ -r /etc/default/mysql ] && . /etc/default/mysql

case "$1" in
	start)
		if [ ! -d $MYSQL_DIR/mysql ] ; then
			echo "Creating MySQL system tables..."
			mysql_install_db --user=$MYSQL_USER --ldata=$MYSQL_DIR
		fi

		# mysqld runs as user mysql, but /run is only writable by root
		# so create a subdirectory for mysql.
		install -d -o mysql -g root -m 0755 /run/mysql

		# We don't use start-stop-daemon because mysqld has
		# its own wrapper script.
		printf "Starting mysql..."
		/usr/bin/mysqld_safe --pid-file=/run/mysql/mysqld.pid &
		echo "done."
		;;
	stop)
		printf "Stopping mysql..."
		if test -f /run/mysql/mysqld.pid ; then
			kill `cat /run/mysql/mysqld.pid`
		fi
		echo "done."
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: /etc/init.d/mysqld {start|stop|restart}"
		;;
esac
