#!/bin/sh
#
# start redis
#

start() {
	echo -n "Starting redis: "
	umask 077
	start-stop-daemon -S -q -c redis:redis -b \
		--exec /usr/bin/redis-server -- /etc/redis.conf
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping redis: "
	/usr/bin/redis-cli shutdown
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
