#!/bin/sh
#
# Starts irqbalance
#

EXEC="/usr/sbin/irqbalance"
ARGS=""
PID="/var/run/irqbalance.pid"

case "$1" in
    start)
	echo -n "Starting irqbalance: "
	start-stop-daemon -S -q -x $EXEC -- $ARGS
	if [ $? != 0 ]; then
	    echo "FAILED"
	    exit 1
	else
	    echo "OK"
	fi
	pidof irqbalance > $PID
	;;
    stop)
	echo -n "Stopping irqbalance: "
	start-stop-daemon -K -q -p $PID
	echo "OK"
	;;
    restart|reload)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
