#!/bin/sh
#
# Starts pulseaudio.
#


start() {
	printf "Starting pulseaudio: "
	umask 077
	/usr/bin/pulseaudio \
		--system \
		--daemonize \
		--disallow-module-loading \
		--disallow-exit \
		--exit-idle-time=-1 \
		--use-pid-file \
		--disable-shm
	echo "OK"
}
stop() {
	printf "Stopping pulseaudio: "
	PULSE_RUNTIME_PATH=/var/run/pulse /usr/bin/pulseaudio --kill
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

