#!/bin/sh
#
# Starts pulseaudio.
#


start() {
	echo -n "Starting pulseaudio: "
	umask 077
	/usr/bin/pulseaudio --system --daemonize
	echo "OK"
}
stop() {
	echo -n "Stopping pulseaudio: "
	pulseaudio --kill
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

