#!/bin/sh
#
# run pango-querymodules if needed

FILE=/etc/pango/pango.modules

case "$1" in
     start|"")
	if [ ! -f $FILE ] ; then
	   mkdir -p /etc/pango
	   /usr/bin/pango-querymodules > "$FILE"
	fi
	;;
    stop)
	;;
    *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac