#!/bin/sh
#
# Starts lighttpd.
#
NAME=lighttpd
DAEMON=/usr/sbin/$NAME
PID_FILE="/var/run/$NAME.pid"
CONF_FILE="/etc/$NAME/$NAME.conf"

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

start() {
	printf "Starting lighttpd: "
	start-stop-daemon -S -q -p $PID_FILE --exec $DAEMON -- -f $CONF_FILE
	echo "OK"
}
stop() {
	printf "Stopping lighttpd: "
	start-stop-daemon -K -q -p $PID_FILE
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

