#!/bin/sh

project_directory=$1
toolchain_prefix=$2
architecture=$3

TOOLCHAIN_ECLIPSE_FILE=${HOME}/.buildroot-eclipse.toolchains

if test -f ${TOOLCHAIN_ECLIPSE_FILE} ; then
    mv ${TOOLCHAIN_ECLIPSE_FILE} ${TOOLCHAIN_ECLIPSE_FILE}.tmp
    cat ${TOOLCHAIN_ECLIPSE_FILE}.tmp | while read toolchain ; do
	path=$(echo ${toolchain} | cut -f1 -d ':')
        # Filter lines corresponding to still existing projects
	echo "Testing ${path} ..."
	if ! test -d ${path} ; then
	    continue
	fi
	# .. and the current project
	if test ${path} = ${project_directory} ; then
	    continue
	fi
	echo ${toolchain} >> ${TOOLCHAIN_ECLIPSE_FILE}
    done
    rm ${TOOLCHAIN_ECLIPSE_FILE}.tmp
fi

# Add the toolchain
echo "${project_directory}:${toolchain_prefix}:${architecture}" >> ${TOOLCHAIN_ECLIPSE_FILE}
