POLARSSL_SITE = http://polarssl.org/code/releases/
POLARSSL_VERSION = 1.1.4
POLARSSL_SOURCE = polarssl-$(POLARSSL_VERSION)-gpl.tgz
POLARSSL_CONF_OPT = \
	-DUSE_SHARED_POLARSSL_LIBRARY=ON \
	-DUSE_STATIC_POLARSSL_LIBRARY=ON \
	-DBUILD_TESTS=OFF \
	-DBUILD_PROGRAMS=$(if $(BR2_PACKAGE_POLARSSL_PROGRAMS),ON,OFF)

POLARSSL_INSTALL_STAGING = YES

$(eval $(cmake-package))

