#!/bin/sh
#
# minidlnad        Starts minidlnad.
#

start() {
	printf "Starting minidlna: "
	umask 077
	start-stop-daemon -S -q -p /var/run/minidlna/minidlna.pid \
		--exec /usr/sbin/minidlnad -- "$@"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping minidlna: "
	start-stop-daemon -K -q -p /var/run/minidlna/minidlna.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	# Sleep needed for minidlna to restart properly
	sleep 1
	start "$@"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  force-reload)
	restart -R
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}"
	exit 1
esac

exit $?
