#!/bin/sh
#
# Upload microcode into the processor.
#

MICROCODE_DIR="/lib/firmware/intel-ucode"

case "$1" in
  start)
	echo "Starting iucode-tool:"
	/usr/sbin/iucode_tool -k "$MICROCODE_DIR"
	echo "done"
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
