#!/bin/sh
#
# Upload microcode into the processor.
#

MICROCODE_DIR="/lib/firmware/intel-ucode"

start() {
	printf 'Starting iucode-tool: '
	/usr/sbin/iucode_tool -q -k "$MICROCODE_DIR"
	status="$?"
	if [ "$status" = 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

case "$1" in
	start)
		start;;
	stop|restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
