#!/bin/sh

MOTIONEYE_CONF_DIR=/data/etc/

enabled() {
    if [ $(ls -1 $MOTIONEYE_CONF_DIR/thread-*.conf 2>/dev/null| wc -l) != 1 ]; then
        return 1
    fi
    
    if ! grep '# @proto mjpeg' $MOTIONEYE_CONF_DIR/thread-1.conf &>/dev/null; then
        return 1
    fi
    
    if ! grep -E '# @url http://(.*)127.0.0.1:' $MOTIONEYE_CONF_DIR/thread-1.conf &>/dev/null; then
        return 1
    fi
    
    return 0
}

enabled || exit 0

start() {
    echo -n "Starting streameye: "
    streameye.sh start
    echo "done"
}

stop() {
    echo -n "Shutting down streameye: "
    streameye.sh stop
    echo "done"
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

