#! /bin/sh

[ -f /usr/bin/input-event-daemon ] || exit 0

start() {
	echo -n "Starting input-event-daemon: "
	input-event-daemon
	echo "done"
}


stop() {
	echo -n "Stopping input-event-daemon: "
	killall input-event-daemon
	echo "done"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
