#!/bin/sh

# Build a ramdisk to overlay on /dev so we can scribble on it
# all we want without needing rw access to the underlying filesystem

SIZE=140
INODES=1000

echo -n "Building device ramdisk: "

/bin/umount /dev/ram1 >/dev/null 2>&1

/bin/dd if=/dev/zero of=/dev/ram1 bs=1k count=$SIZE >/dev/null 2>&1
if [ $? != 0 ] ; then
	echo "failed."
	exit 1;
fi

/sbin/mkfs.minix -n30 -i$INODES /dev/ram1 $SIZE >/dev/null 2>&1
if [ $? != 0 ] ; then
	echo "failed."
	exit 1;
fi

/bin/mount /dev/ram1 /mnt -t minix -o rw >/dev/null 2>&1
if [ $? != 0 ] ; then
	echo "failed."
	exit 1;
fi

/bin/cp -a /dev/* /mnt >/dev/null 2>&1
if [ $? != 0 ] ; then
	echo "failed."
	exit 1;
fi

/bin/umount /mnt >/dev/null 2>&1
if [ $? != 0 ] ; then
	echo "failed."
	exit 1;
fi

/bin/mount /dev/ram1 /dev -t minix -o rw >/dev/null 2>&1
if [ $? != 0 ] ; then
	echo "failed."
	exit 1;
else
	echo "done." 
fi

exit 0
