#! /bin/sh

[ -f /sbin/portmap ] || exit 0

start() {
	printf "Starting portmap: "
	portmap
	mkdir -p /var/lock/subsys
	touch /var/lock/subsys/portmap
	echo "done"
}


stop() {
        printf "Stopping portmap: "
	echo
        killall portmap
        rm -rf /var/lock/subsys
	echo "done"
}

restart() {
	stop
	start
	rm -f /var/run/portmap.state
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
