#!/bin/sh
#
# Start mdev....
#


start() {
	echo "Starting mdev..."
	echo /sbin/mdev >/proc/sys/kernel/hotplug
	/sbin/mdev -s
	# coldplug modules
	find /sys/ -name modalias -print0 | \
		xargs -0 sort -u | \
		tr '\n' '\0' | \
		xargs -0 modprobe -abq
}

case "$1" in
  start)
	"$1"
	;;
  *)
	echo "Usage: $0 start"
	exit 1
esac

exit $?
