#!/bin/sh

# Allow a few customizations from a config file
test -r /etc/default/NetworkManager && . /etc/default/NetworkManager

PID=`pidof NetworkManager`
case "$1" in
	start)
		printf "Starting NetworkManager ... "
		[ ! -d /var/run/NetworkManager ] && install -d /var/run/NetworkManager
		if [ -z "$PID" ]; then
			/usr/sbin/NetworkManager $NETWORKMANAGER_ARGS
		fi
		if [ ! -z "$PID" -o $? -gt 0 ]; then
			echo "failed!"
		else
			echo "done."
		fi
		;;
	stop)
		printf "Stopping NetworkManager ... "
			[ ! -z "$PID" ] && kill $PID > /dev/null 2>&1
		if [ $? -gt 0 ]; then
			echo "failed!"
		else
			echo "done."
		fi
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart|sleep|wake}"
		;;
esac
exit 0



