#!/bin/sh
#
# Start ptpd
#

case "$1" in
  start)
	echo -n "Starting ptpd: "
	start-stop-daemon -S -q -x /usr/sbin/ptpd -- -S
	if [ $? != 0 ]; then
		echo "FAILED"
		exit 1
	else
		echo "OK"
	fi
	;;
  stop)
	echo -n "Stopping ptpd: "
	start-stop-daemon -K -q -x /usr/sbin/ptpd
	echo "OK"
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
