#!/bin/sh

# we don't have the codepage kernel modules compiled in, so we have to manually insert them
mkdir /system
mount /dev/mmcblk1p2 /system
/system/bin/busybox insmod /system/lib/modules/*/kernel/fs/nls/nls_*.ko

