#!/bin/sh
#
case "$1" in
       start)
                modprobe pfe
                ;;
        stop)
                ;;
        restart|reload)
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
