#!/bin/sh

XDM_BIN=/usr/bin/xdm

case "$1" in
    start)
        echo -n "Starting XDM: "
        $XDM_BIN
        echo "done"
        ;;
    stop)
	echo "Stopping XDM"
        killall -q xdm
        ;;
    restart)
	$0 stop
	$0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
