#!/bin/bash

CHALLENGE="$1"
PORT=80
LIFETIME=10

if [[ -z "${CHALLENGE}" ]]; then
    echo "Usage $0 <challenge>"
    exit 1
fi

function make_response() {
    echo -en "HTTP/1.1 200 OK\r\n"
    echo -en "Content-Length: ${#CHALLENGE}\r\n"
    echo -en "Content-Type: text/plain\r\n"
    echo -en "Connection: close\r\n\r\n${CHALLENGE}"
}

start_time=$(date +%s)
echo "Dumb httpd started"
while true; do
    make_response | nc -l -w "${LIFETIME}" -p ${PORT} >/dev/null
    if (( $(date +%s) - ${start_time} > ${LIFETIME} )); then
        break
    fi
done
echo "Dumb httpd exit"
