#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <account/project>" 1>&2
    exit -1
fi

opts="-s -S -f"
test -n "$FW_USERNAME" && opts+=" --user $FW_USERNAME:$FW_PASSWORD"
url=https://api.github.com/repos/$1/releases
jq_expr='.[] | {version: .name, prerelease: .prerelease | tostring} + (.assets[] | {name: .name | split("-")[1], url: .browser_download_url}) | flatten | join("|")'

curl $opts $url | jq --raw-output "$jq_expr"
exit ${PIPESTATUS[0]}

