#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <account/project>" 1>&2
    exit -1
fi

opts="-s -S -f"
test -n "$GITHUB_USERNAME" && opts+=" --user $GITHUB_USERNAME:$GITHUB_PASSWORD"
url=https://api.github.com/repos/$1/releases
jq_expr='.[] | {version: .name, prerelease: .prerelease | tostring, name: .assets[].name | capture("[^-]+-(?<b>[^-]+)") | flatten, asset: .assets[].browser_download_url} | flatten | join("|")'

curl $opts $url | jq --raw-output "$jq_expr"
exit ${PIPESTATUS[0]}

