#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <account/project>" 1>&2
    exit -1
fi

opts="-s -S -f"
test -n "${FW_USERNAME}" && opts+=" --user ${FW_USERNAME}:${FW_PASSWORD}"
releases_url=https://api.github.com/repos/$1/releases

# Get release info via GitHub API
releases=$(curl ${opts} ${releases_url})
test $? == 0 || exit 1

# Format release lines
jq_expr='.[] | {version: .name, prerelease: .prerelease | tostring} + 
         (.assets[] | {name: .name | split("-")[1], url: .browser_download_url}) + 
         ({date: .created_at | split("T")[0]}) +
         ({published: true})
         | flatten | join("|")'

jq --raw-output "${jq_expr}" <<< ${releases}
exit $?
