#!/bin/bash

# expected final S3 URL: 
#    https://{bucket}.s3.amazonaws.com/${path}/${version}/${os_short_name}-${board}-${version}.img.xz

if [ -z "$1" ]; then
    echo "Usage: $0 <bucket/path>" 1>&2
    exit -1
fi

bucket_path=$1
bucket=$(echo ${bucket_path} | cut -d '/' -f 1)
path=${bucket_path:${#bucket} + 1}

opts="-s -S -f"
test -n "${FW_USERNAME}" && opts+=" --user ${FW_USERNAME}:${FW_PASSWORD}"
url="https://${bucket}.s3.amazonaws.com"

xml_result=$(curl ${opts} "${url}?list-type=2&prefix=${path}")
keys=$(echo "${xml_result}" | grep -oE '<Key>[^<]+<\/Key>' | sed 's/<Key>\(.*\)<\/Key>/\1/')
dates=$(echo "${xml_result}" | grep -oE '<LastModified>[^<]+<\/LastModified>' | sed 's/<LastModified>\(.*\)<\/LastModified>/\1/')
dates=(${dates})
files=(${keys})

i=0
for file in ${files[*]}; do
    version=$(echo ${file:${#path} + 1} | cut -d '/' -f 1)
    fname=$(basename ${file})
    i=$((i + 1))
    if [[ -z "${fname}" ]]; then
        continue
    fi

    prerelease=false
    if [[ "${version}" =~ ^.*[abc]\.?[0-9]+$ ]] || # e.g. 0.4.1b2, 0.4.1b.2, 0.4.1-b.2
       [[ "${version}" =~ ^.*(alpha|beta|rc)\.?[0-9]+$ ]] || # e.g. 0.4.1beta2, 0.4.1beta.2, 0.4.1-beta.2
       [[ "${version}" =~ ^(dev|nightly).*$ ]]; then # e.g. dev20180314, nightly20180314
        prerelease=true
    fi

    final_url=${url}/${path}/${version}/${fname}
    board=$(echo ${fname} | cut -d '-' -f 2)
    date=$(echo ${dates[${i}]} | cut -d 'T' -f 1)
    
    echo "${version}|${prerelease}|${board}|${final_url}|${date}"
done | sort -t '|' -k 5,3 -r
