#!/bin/sh
#
# Starts rsyslog.
#

start() {
	echo -n "Starting rsyslog daemon: "
	umask 077
	start-stop-daemon -S -q -p /var/run/rsyslogd.pid --exec /usr/sbin/rsyslogd
	echo "OK"
}
stop() {
	echo -n "Stopping rsyslog daemon: "
	start-stop-daemon -K -q -p /var/run/rsyslogd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

