#!/bin/sh

NAME=boinc_client
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/$NAME

start() {
	printf "Starting $NAME: "
	start-stop-daemon -S -q -m -b -p $PIDFILE --exec $DAEMON
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping $NAME: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
