#!/bin/bash

test -n "$OS_VERSION" || source /etc/init.d/base

case "$1" in
    start)
        sleep 2
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?

