#!/bin/sh
#
# Starts neard
#

NAME=neard

case "$1" in
  start)
    printf "Starting $NAME: "
    start-stop-daemon -S -q -p /var/run/${NAME}.pid -x /usr/libexec/nfc/neard -- -d '*'
    echo "OK"
    ;;
  stop)
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -p /var/run/${NAME}.pid
    echo "OK"
    ;;
  restart|reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
