name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-2020 flake8-bugbear
                         flake8-comprehensions isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101,B105,B108,B110,B112,B306,B310,B404,B506,B602,B603,B605,B607 .
      - run: black --check . || true
      - run: codespell || true  # --ignore-words-list="" --skip="*.css,*.js,*.lock"
      - run: flake8 --ignore=B001,B006,B007,C402,C404,C408,E117,E121,E126,E128,E131,E203,E241,E261,E302,E303,E722,E741,F401,F841,W291,W293,W391,W504,W605
                    --max-complexity=26 --max-line-length=190 --show-source --statistics .
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt || pip install --editable .  || pip install . || true
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --explicit-package-bases --ignore-missing-imports --install-types --namespace-packages --non-interactive . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py37-plus **/*.py || true
      - run: safety check
