#!/bin/sh
#
# Start/stop nginx
#

PIDFILE=/var/run/nginx.pid

case "$1" in
  start)
	echo "Starting nginx..."
	mkdir -p /var/log/nginx /var/tmp/nginx
	start-stop-daemon -S -x /usr/sbin/nginx -p $PIDFILE
	;;
  stop)
	echo -n "Stopping nginx..."
	start-stop-daemon -K -o -p $PIDFILE
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
