#!/bin/sh
#
# Start chrony

[ -f /etc/chrony.conf ] || exit 0

case "$1" in
  start)
	echo "Starting chrony: "
	chronyd && echo "OK" || echo "FAIL"
	;;
  stop)
	echo -n "Stopping chrony: "
	killall chronyd && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	sleep 1
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
