#!/bin/sh
#
# Controls lldpd.
#

case $1 in
    start)
	printf "Starting lldpd: "
	start-stop-daemon -S -q -p /var/run/lldpd.pid --exec /usr/sbin/lldpd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Stopping lldpd: "
	start-stop-daemon -K -q -p /var/run/lldpd.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
